#!/bin/sh

export DB_USER=$1
export DB_PASS=$2
export DATABASE_URL="postgres://$1:$2@localhost:5432/carpools"
export MAPBOX_KEY=<MAPBOX_TOKEN>
export GOOGLE_CLIENT_ID=<GOOGLE_CLIENT_ID>

mvn package

./run
